version: "3"

services:
  db:
    build: ./Docker/mysql
    volumes:
      - db-store:/var/lib/mysql
  app:
    build: ./Docker/php
    volumes:
      - .:/work
    depends_on:
      - db
  web:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - .:/work
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work
    depends_on:
      - app

volumes:
  db-store:
